[package]
name = "taskerie-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_norway = "0"
itertools = "0"
indexmap = { version = "2", features = ["serde"] }
regex = "1"
subprocess = "0"

anyhow.workspace = true
log.workspace = true
