[package]
name = "taskerie"
version = "0.1.0"
edition = "2024"

[dependencies]
taskerie-core.path = "../taskerie-core"

inquire = "0"
pretty_env_logger = "0"

log.workspace = true
anyhow.workspace = true
